server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 安全认证的配置
security:
  basic:
    enabled: true
  user:
    name: admin  # 用户名
    password: 123456   # 用户密码
